/* eslint-disable */
/**
 * FDO Manager Service API
 * The FDO Manager Service API for creating FAIR Digital Objects.
 *
 * The version of the OpenAPI document: 0.1
 * Contact: t.fitschen@indiscale.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

